// app/layout.tsx
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // includes light & bold
  variable: "--font-poppins",
  display: "swap",
});

// ✅ Local Font (Uxum) — All weights in one declaration
const uxum = localFont({
  src: [
    {
      path: "../../public/fonts/uxumlight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/uxumregular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/uxumbold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-uxum",
  display: "swap",
});

const neue = localFont({
  src: [
    {
      path: "../../public/fonts/NeueMontreal-Medium.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/NeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/NeueMontreal-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-neue",
  display: "swap",
});

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${uxum.variable} ${neue.variable}`}
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}
